name: flutter_bloc_firebase_starter
description: "A Flutter project with integration of firebase and bloc state
  management following clean architecture."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.0
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  dots_indicator: ^3.0.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.10
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_sign_in: ^6.2.2
  in_app_review: ^2.0.10
  injectable: ^2.5.0
  intl: ^0.20.1
  lottie: ^3.3.0
  package_info_plus: ^8.1.2
  pinput: ^5.0.0
  share_plus: ^10.1.3
  shared_preferences: ^2.3.4
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/social/
    - assets/svg/

  fonts:
    - family: LibreFranklin
      fonts:
        - asset: assets/fonts/Libre_Franklin/static/LibreFranklin-Black.ttf
          weight: 900
        - asset: assets/fonts/Libre_Franklin/static/LibreFranklin-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Libre_Franklin/static/LibreFranklin-Bold.ttf
          weight: 700
        - asset: assets/fonts/Libre_Franklin/static/LibreFranklin-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Libre_Franklin/static/LibreFranklin-Medium.ttf
          weight: 500
        - asset: assets/fonts/Libre_Franklin/static/LibreFranklin-Regular.ttf
          weight: 400
        - asset: assets/fonts/Libre_Franklin/static/LibreFranklin-Light.ttf
          weight: 300
        - asset: assets/fonts/Libre_Franklin/static/LibreFranklin-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Libre_Franklin/static/LibreFranklin-Thin.ttf
          weight: 100
